### ISSUE TITLE
Feedback for Quick-Start

### ISSUE THREAD

**Issue by escudero89** [bem-site/bem-method#579]
Hello,

I have two suggestions to make regarding your article: [BEM Methodology: Quick Start](https://en.bem.info/methodology/quick-start/)

# Modifier

> (... key-value) Used when the modifier value is important. For example, "a menu with the islands design theme": **menu_theme_islands**.
>
> The structure of the modifier's full name follows the pattern:
>
> block-name_modifier-name_modifier-value
> block-name__element-name_modifier-name_modifier-value

From that info, shouldn't it be `menu_theme-islands`, since the `name_modifier` is (as I understand) `menu_theme`, and its value is `islands`?

# Environment

This is a minor suggestion:

> In this example, we combined the behavior and styles of the search-form block and the search-form element from the header block. This approach allows us to set the external geometry and positioning in the header__search-form element, while the search-form block itself remains universal. As a result, we can use the block in any other environment, because it doesn't specify any **padding**. This is why we can call it independent.

Shouldn't it be **margin**, since that's what the text says above (in `block`):

> The block shouldn't influence its environment, meaning you shouldn't set the external geometry (**margin**) or positioning for the block.

---

Anyways, thanks for this detailed guide.

Greetings!

**Comment by innabelaya** [comment]
@escudero89 Hi! Here is some description:
> From that info, shouldn't it be `menu_theme-islands`, since the `name_modifier` is (as I understand) `menu_theme`, and its value is `islands`?

The modifier name is separated from the block or element name by a single underscore (_). To separate several words in the modifier's name or in the modifier's value we use hyphen (-). 
Your example means that the name of the modifier is `theme-islands`, but in the document we are talking about the `theme` modifier with `islands` value. The correct entry looks like `menu_theme_islands`.


> Shouldn't it be **margin**, since that's what the text says above (in `block`):

Thank you! Of course you're right. Fixed in https://github.com/bem-site/bem-method/pull/601/commits/bb6d863ccc1234a1cec9abf64c0513a26d51b054
